python3 receive_logs_direct.py info error
